/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_register;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;

public class Register_Form extends javax.swing.JFrame {

    /**
     * Creates new form Register_Form
     */
    public Register_Form() {
        initComponents();
        
        //Center the form
        this.setLocationRelativeTo(null);
        
        //Create black border for close and minimize jlabels
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.BLACK);
        jLabel_minimize.setBorder(label_border);
        jLabel_close.setBorder(label_border);
        
        //For selecting only one button group in gender
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButton_male);
        bg.add(jRadioButton_female);
        bg.add(jRadioButton_other);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jButton_register = new javax.swing.JButton();
        jLabel_fullname = new javax.swing.JLabel();
        jTextField_firstname = new javax.swing.JTextField();
        jLabel_lastname = new javax.swing.JLabel();
        jTextField_lastname = new javax.swing.JTextField();
        jTextField_age = new javax.swing.JTextField();
        jLabel_age = new javax.swing.JLabel();
        jLabel_address = new javax.swing.JLabel();
        jTextField_address = new javax.swing.JTextField();
        jTextField_street = new javax.swing.JTextField();
        jLabel_street = new javax.swing.JLabel();
        jTextField_pincode = new javax.swing.JTextField();
        jLabel_pincode = new javax.swing.JLabel();
        jLabel_dob = new javax.swing.JLabel();
        jLabel_gender = new javax.swing.JLabel();
        jLabel_department = new javax.swing.JLabel();
        jComboBox_department = new javax.swing.JComboBox<>();
        jLabel_designation = new javax.swing.JLabel();
        jComboBox_designation = new javax.swing.JComboBox<>();
        jRadioButton_female = new javax.swing.JRadioButton();
        jRadioButton_male = new javax.swing.JRadioButton();
        jRadioButton_other = new javax.swing.JRadioButton();
        jLabel_phone = new javax.swing.JLabel();
        jTextField_phone = new javax.swing.JTextField();
        jDateChooser_dob = new com.toedter.calendar.JDateChooser();
        jLabel_city = new javax.swing.JLabel();
        jTextField_city = new javax.swing.JTextField();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        jPanel11.setBackground(new java.awt.Color(51, 0, 204));

        jPanel12.setBackground(new java.awt.Color(102, 102, 255));

        jButton_register.setBackground(new java.awt.Color(0, 0, 0));
        jButton_register.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_register.setForeground(new java.awt.Color(255, 255, 255));
        jButton_register.setText("Register");
        jButton_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_registerMouseExited(evt);
            }
        });
        jButton_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registerActionPerformed(evt);
            }
        });

        jLabel_fullname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_fullname.setText("First Name*");

        jTextField_firstname.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_firstname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_firstnameActionPerformed(evt);
            }
        });

        jLabel_lastname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_lastname.setText("Last Name*");

        jTextField_lastname.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_lastname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lastnameActionPerformed(evt);
            }
        });

        jTextField_age.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_age.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ageActionPerformed(evt);
            }
        });
        jTextField_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ageKeyTyped(evt);
            }
        });

        jLabel_age.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_age.setText("Age");

        jLabel_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_address.setText("Address");

        jTextField_address.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_addressActionPerformed(evt);
            }
        });

        jTextField_street.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_street.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_streetActionPerformed(evt);
            }
        });

        jLabel_street.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_street.setText("Street");

        jTextField_pincode.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_pincode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_pincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pincodeActionPerformed(evt);
            }
        });
        jTextField_pincode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_pincodeKeyTyped(evt);
            }
        });

        jLabel_pincode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_pincode.setText("Pincode");

        jLabel_dob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_dob.setText("D.O.B*");

        jLabel_gender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_gender.setText("Gender*");

        jLabel_department.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_department.setText("Department*");

        jComboBox_department.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox_department.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "Marketing", "Financial", "Human Resources", "Administration", "Production", "Logistics", "Security" }));

        jLabel_designation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_designation.setText("Designation*");

        jComboBox_designation.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox_designation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_designation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineer", "Trainee Engineer", "System Analyst", "Programmer Analyst", "Project Manager", "Architect", "Technical Specialist", "Business Analyst", "Director", "Vice President", "President", "CEO" }));
        jComboBox_designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_designationActionPerformed(evt);
            }
        });

        jRadioButton_female.setBackground(new java.awt.Color(102, 102, 255));
        jRadioButton_female.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_female.setText("Female");

        jRadioButton_male.setBackground(new java.awt.Color(102, 102, 255));
        jRadioButton_male.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_male.setText("Male");
        jRadioButton_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_maleActionPerformed(evt);
            }
        });

        jRadioButton_other.setBackground(new java.awt.Color(102, 102, 255));
        jRadioButton_other.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_other.setText("Other");
        jRadioButton_other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_otherActionPerformed(evt);
            }
        });

        jLabel_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_phone.setText("Phone*");

        jTextField_phone.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_phoneActionPerformed(evt);
            }
        });
        jTextField_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_phoneKeyTyped(evt);
            }
        });

        jDateChooser_dob.setBackground(new java.awt.Color(204, 204, 255));
        jDateChooser_dob.setDateFormatString("dd MMM yyyy");
        jDateChooser_dob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel_city.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_city.setText("City");

        jTextField_city.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_city.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 121, Short.MAX_VALUE)
                .addComponent(jButton_register, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_dob)
                            .addComponent(jLabel_pincode))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_pincode)
                            .addComponent(jDateChooser_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel12Layout.createSequentialGroup()
                                    .addComponent(jLabel_fullname)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel12Layout.createSequentialGroup()
                                    .addComponent(jLabel_phone)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                    .addComponent(jLabel_lastname)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel_address)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel_street)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_street, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel_age)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel_city)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_city, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel_department)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel_designation)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel_gender)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_male, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_female, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_other)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_fullname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_lastname))
                .addGap(12, 12, 12)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_phone))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_age))
                .addGap(12, 12, 12)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_street))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_city))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_pincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_pincode))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_gender)
                    .addComponent(jRadioButton_female)
                    .addComponent(jRadioButton_male)
                    .addComponent(jRadioButton_other))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_department)
                    .addComponent(jComboBox_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_designation)
                    .addComponent(jComboBox_designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton_register, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel_minimize.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_minimize.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setText("-");
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });

        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        jLabel_title.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_title.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel_title.setText("REGISTER");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_title)
                .addGap(75, 75, 75)
                .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_title, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_registerMouseEntered
        //Setting color for mouse entered
        jButton_register.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jButton_registerMouseEntered

    private void jButton_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_registerMouseExited
        //Setting color for mouse exit
        jButton_register.setBackground(Color.BLACK);
    }//GEN-LAST:event_jButton_registerMouseExited

    private void jButton_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registerActionPerformed
      
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection cn = null;
            PreparedStatement st = null;
            ResultSet rs = null;
            
            
            //Get the username and password
            String fname = jTextField_firstname.getText();
            String lname = jTextField_lastname.getText();
            String phone = jTextField_phone.getText();
            String age = jTextField_age.getText();
            String address = jTextField_address.getText();
            String street = jTextField_street.getText();
            String city = jTextField_city.getText();
            String pincode = jTextField_pincode.getText();
            //Convert date_of_birth to string
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dob = sdf.format(jDateChooser_dob.getDate());
            
            String dep = jComboBox_department.getSelectedItem().toString();
            String desig = jComboBox_designation.getSelectedItem().toString();
            
            String gender;
            if(jRadioButton_male.isSelected())
            {
                gender = "Male";
            }
            else if(jRadioButton_female.isSelected())
            {
                gender = "Female";
            }
            else
            {
                gender = "Other";
            }
            
            //Create a INSERT query to insert data on the database
            String query = "INSERT INTO regs VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
            cn = MyCon.ConnectDB();
            st = cn.prepareStatement(query);
            st.setString(1,fname);
            st.setString(2,lname);
            st.setString(3,phone);
            st.setString(4,age);
            st.setString(5,address);
            st.setString(6,street);
            st.setString(7,city);
            st.setString(8,pincode);
            st.setString(9,dob);
            st.setString(10,gender);
            st.setString(11,dep);
            st.setString(12,desig);
          
            boolean b2 = verifyFields();
            
            if(b2==true)
            {
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "You have been registered");
            
                //Progress to HomePage form
                Home_Page hp = new Home_Page();
                hp.setVisible(true);
                hp.pack();
                hp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                //Close Login form
                this.dispose(); 
            
            
            }
            else{
                JOptionPane.showMessageDialog(null, "Retry!!!");   
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_registerActionPerformed

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.WHITE);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.WHITE);//Set color of the icon
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.BLACK);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.WHITE);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.BLACK);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jTextField_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_firstnameActionPerformed

    private void jTextField_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lastnameActionPerformed

    private void jTextField_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ageActionPerformed

    private void jTextField_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addressActionPerformed

    private void jTextField_streetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_streetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_streetActionPerformed

    private void jTextField_pincodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pincodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pincodeActionPerformed

    private void jComboBox_designationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_designationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_designationActionPerformed

    private void jRadioButton_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_maleActionPerformed

    private void jRadioButton_otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_otherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_otherActionPerformed

    private void jTextField_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phoneActionPerformed

    private void jTextField_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phoneKeyTyped
        //Allow only numbers
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_phoneKeyTyped

    private void jTextField_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ageKeyTyped
        //Allow only numbers
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_ageKeyTyped

    private void jTextField_pincodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_pincodeKeyTyped
        //Allow only numbers
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_pincodeKeyTyped

    private void jTextField_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cityActionPerformed

    
    //Create a function to check for mandatory fields
    private boolean verifyFields()
    {
        String fname = jTextField_firstname.getText();
        String lname = jTextField_lastname.getText();
        String phone = jTextField_phone.getText();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dob = sdf.format(jDateChooser_dob.getDate());

        //Check empty fields
        if((fname.trim().equals("")||lname.trim().equals("")||phone.trim().equals(""))
                ||(!(jRadioButton_male.isSelected()||jRadioButton_female.isSelected()
                ||jRadioButton_other.isSelected())))
        {
            JOptionPane.showMessageDialog(null, "Mandatory fields are empty","Empty Fields",2);
            return false;
        }
        else
        {
            return true;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_register;
    private javax.swing.JComboBox<String> jComboBox_department;
    private javax.swing.JComboBox<String> jComboBox_designation;
    private com.toedter.calendar.JDateChooser jDateChooser_dob;
    private javax.swing.JLabel jLabel_address;
    private javax.swing.JLabel jLabel_age;
    private javax.swing.JLabel jLabel_city;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_department;
    private javax.swing.JLabel jLabel_designation;
    private javax.swing.JLabel jLabel_dob;
    private javax.swing.JLabel jLabel_fullname;
    private javax.swing.JLabel jLabel_gender;
    private javax.swing.JLabel jLabel_lastname;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_phone;
    private javax.swing.JLabel jLabel_pincode;
    private javax.swing.JLabel jLabel_street;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JRadioButton jRadioButton_female;
    private javax.swing.JRadioButton jRadioButton_male;
    private javax.swing.JRadioButton jRadioButton_other;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_age;
    private javax.swing.JTextField jTextField_city;
    private javax.swing.JTextField jTextField_firstname;
    private javax.swing.JTextField jTextField_lastname;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_pincode;
    private javax.swing.JTextField jTextField_street;
    // End of variables declaration//GEN-END:variables
}
