/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_register;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class ShowInfo_Form extends javax.swing.JFrame {

    /**
     * Creates new form ShowInfo_Form
     */
    public ShowInfo_Form() {
        initComponents();
        
        //Sets location of form to the center of the screen
        this.setLocationRelativeTo(null);
        
        //Create black border for close and minimize jlabels
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.BLACK);
        jLabel_minimize.setBorder(label_border);
        jLabel_close.setBorder(label_border);
        
        //Function to show data
        show_user();
    }
    
    public ArrayList<User> userList()
    {
        ArrayList<User> userList = new ArrayList<>();
         try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3308/mydb","Ritwik","qwerty");
                String query = "SELECT * FROM regs";
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(query);
                User user;
                while (rs.next())
                {
                    user = new User(rs.getString("first_name"),rs.getString("last_name"),rs.getString("phone"),
                            rs.getString("age"),rs.getString("address"),rs.getString("street")
                            ,rs.getString("city"),rs.getString("pincode"),rs.getString("dob")
                            ,rs.getString("gender"),rs.getString("department"),rs.getString("designation"));
                    userList.add(user);
                }
             }
         catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
          return  null;
      }
         return userList;
    }
    
    public void show_user()
    {
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel)jTable_show.getModel();
        Object[] row = new Object[12];
        for(int i=0;i<list.size();i++)
        {
            row[0] = list.get(i).getfname();
            row[1] = list.get(i).getlname();
            row[2] = list.get(i).getphone();
            row[3] = list.get(i).getage();
            row[4] = list.get(i).getaddress();
            row[5] = list.get(i).getstreet();
            row[6] = list.get(i).getcity();
            row[7] = list.get(i).getpincode();
            row[8] = list.get(i).getdob();
            row[9] = list.get(i).getgender();
            row[10] = list.get(i).getdepartment();
            row[11] = list.get(i).getdesignation();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_fullname5 = new javax.swing.JLabel();
        jTextField_firstname5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_show = new javax.swing.JTable();
        jLabel_delete = new javax.swing.JLabel();
        jLabel_update = new javax.swing.JLabel();
        jLabel_back = new javax.swing.JLabel();
        jLabel_fullname = new javax.swing.JLabel();
        jTextField_firstname = new javax.swing.JTextField();
        jTextField_lastname = new javax.swing.JTextField();
        jLabel_lastname = new javax.swing.JLabel();
        jLabel_phone = new javax.swing.JLabel();
        jTextField_phone = new javax.swing.JTextField();
        jLabel_age = new javax.swing.JLabel();
        jTextField_age = new javax.swing.JTextField();
        jTextField_address = new javax.swing.JTextField();
        jLabel_address = new javax.swing.JLabel();
        jLabel_street = new javax.swing.JLabel();
        jTextField_street = new javax.swing.JTextField();
        jTextField_city = new javax.swing.JTextField();
        jLabel_city = new javax.swing.JLabel();
        jLabel_pincode = new javax.swing.JLabel();
        jTextField_pincode = new javax.swing.JTextField();
        jDateChooser_dob = new com.toedter.calendar.JDateChooser();
        jLabel_dob = new javax.swing.JLabel();
        jLabel_gender = new javax.swing.JLabel();
        jRadioButton_male = new javax.swing.JRadioButton();
        jRadioButton_female = new javax.swing.JRadioButton();
        jRadioButton_other = new javax.swing.JRadioButton();
        jComboBox_department = new javax.swing.JComboBox<>();
        jLabel_department = new javax.swing.JLabel();
        jLabel_designation = new javax.swing.JLabel();
        jComboBox_designation = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_search = new javax.swing.JLabel();
        jTextField_lastname1 = new javax.swing.JTextField();
        jLabel_firstnamesearch = new javax.swing.JLabel();
        jLabel_lastnamesearch = new javax.swing.JLabel();
        jTextField_firstnamesearch = new javax.swing.JTextField();
        jTextField_phone1 = new javax.swing.JTextField();
        jLabel_phone1 = new javax.swing.JLabel();

        jLabel_fullname5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_fullname5.setText("First Name");

        jTextField_firstname5.setBackground(new java.awt.Color(255, 204, 204));
        jTextField_firstname5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel_minimize.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_minimize.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setText("-");
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });

        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        jLabel_title.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_title.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel_title.setText("EMPLOYEE DATA");

        jTable_show.setBackground(new java.awt.Color(255, 255, 153));
        jTable_show.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "first_name", "last_name", "phone", "age", "address", "street", "city", "pincode", "dob", "gender", "department", "designation"
            }
        ));
        jTable_show.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_showMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_show);

        jLabel_delete.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel_delete.setText("Delete");
        jLabel_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_deleteMouseExited(evt);
            }
        });

        jLabel_update.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel_update.setText("Update");
        jLabel_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_updateMouseExited(evt);
            }
        });

        jLabel_back.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel_back.setText("Back");
        jLabel_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_backMouseExited(evt);
            }
        });

        jLabel_fullname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_fullname.setText("First Name*");

        jTextField_firstname.setBackground(new java.awt.Color(255, 255, 204));
        jTextField_firstname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_firstnameActionPerformed(evt);
            }
        });

        jTextField_lastname.setBackground(new java.awt.Color(255, 255, 204));
        jTextField_lastname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lastnameActionPerformed(evt);
            }
        });

        jLabel_lastname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_lastname.setText("Last Name*");

        jLabel_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_phone.setText("Phone*");

        jTextField_phone.setBackground(new java.awt.Color(255, 255, 204));
        jTextField_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_phoneActionPerformed(evt);
            }
        });
        jTextField_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_phoneKeyTyped(evt);
            }
        });

        jLabel_age.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_age.setText("Age");

        jTextField_age.setBackground(new java.awt.Color(255, 255, 204));
        jTextField_age.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ageActionPerformed(evt);
            }
        });
        jTextField_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ageKeyTyped(evt);
            }
        });

        jTextField_address.setBackground(new java.awt.Color(255, 255, 204));
        jTextField_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_addressActionPerformed(evt);
            }
        });

        jLabel_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_address.setText("Address");

        jLabel_street.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_street.setText("Street");

        jTextField_street.setBackground(new java.awt.Color(255, 255, 204));
        jTextField_street.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_streetActionPerformed(evt);
            }
        });

        jTextField_city.setBackground(new java.awt.Color(255, 255, 204));
        jTextField_city.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cityActionPerformed(evt);
            }
        });

        jLabel_city.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_city.setText("City");

        jLabel_pincode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_pincode.setText("Pincode");

        jTextField_pincode.setBackground(new java.awt.Color(255, 255, 204));
        jTextField_pincode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_pincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pincodeActionPerformed(evt);
            }
        });
        jTextField_pincode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_pincodeKeyTyped(evt);
            }
        });

        jDateChooser_dob.setBackground(new java.awt.Color(255, 255, 204));
        jDateChooser_dob.setDateFormatString("dd MMM yyyy");
        jDateChooser_dob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel_dob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_dob.setText("D.O.B*");

        jLabel_gender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_gender.setText("Gender*");

        jRadioButton_male.setBackground(new java.awt.Color(255, 204, 0));
        jRadioButton_male.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_male.setText("Male");
        jRadioButton_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_maleActionPerformed(evt);
            }
        });

        jRadioButton_female.setBackground(new java.awt.Color(255, 204, 0));
        jRadioButton_female.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_female.setText("Female");

        jRadioButton_other.setBackground(new java.awt.Color(255, 204, 0));
        jRadioButton_other.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_other.setText("Other");
        jRadioButton_other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_otherActionPerformed(evt);
            }
        });

        jComboBox_department.setBackground(new java.awt.Color(255, 255, 204));
        jComboBox_department.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "Marketing", "Financial", "Human Resources", "Administration", "Production", "Logistics", "Security" }));

        jLabel_department.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_department.setText("Department*");

        jLabel_designation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_designation.setText("Designation*");

        jComboBox_designation.setBackground(new java.awt.Color(255, 255, 204));
        jComboBox_designation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_designation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineer", "Trainee Engineer", "System Analyst", "Programmer Analyst", "Project Manager", "Architect", "Technical Specialist", "Business Analyst", "Director", "Vice President", "President", "CEO" }));
        jComboBox_designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_designationActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel_search.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel_search.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_search.setText("Search");
        jLabel_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_searchMouseExited(evt);
            }
        });

        jTextField_lastname1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField_lastname1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_lastname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lastname1ActionPerformed(evt);
            }
        });
        jTextField_lastname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_lastname1KeyPressed(evt);
            }
        });

        jLabel_firstnamesearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_firstnamesearch.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_firstnamesearch.setText("First Name");

        jLabel_lastnamesearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_lastnamesearch.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_lastnamesearch.setText("Last Name");

        jTextField_firstnamesearch.setBackground(new java.awt.Color(255, 255, 204));
        jTextField_firstnamesearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_firstnamesearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_firstnamesearchActionPerformed(evt);
            }
        });
        jTextField_firstnamesearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_firstnamesearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_firstnamesearchKeyReleased(evt);
            }
        });

        jTextField_phone1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField_phone1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_phone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_phone1ActionPerformed(evt);
            }
        });
        jTextField_phone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_phone1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_phone1KeyTyped(evt);
            }
        });

        jLabel_phone1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_phone1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_phone1.setText("Phone");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel_firstnamesearch)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_firstnamesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel_lastnamesearch)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_lastname1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel_phone1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_search)
                            .addComponent(jTextField_phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_firstnamesearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_firstnamesearch))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_lastname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_lastnamesearch))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_phone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_phone1))
                .addGap(26, 26, 26)
                .addComponent(jLabel_search)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(527, Short.MAX_VALUE)
                .addComponent(jLabel_title)
                .addGap(426, 426, 426)
                .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel_gender)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_male, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_female, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_other))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_department)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_designation)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_address)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_street)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_street, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_age)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_city)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_city, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_phone)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_dob)
                                    .addComponent(jLabel_pincode))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_pincode)
                                    .addComponent(jDateChooser_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_fullname)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_lastname)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(307, 307, 307)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel_delete)
                        .addComponent(jLabel_back))
                    .addComponent(jLabel_update))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_title, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel_update)
                        .addGap(173, 173, 173)
                        .addComponent(jLabel_delete)
                        .addGap(188, 188, 188)
                        .addComponent(jLabel_back)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_fullname))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_lastname))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_phone))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_age))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_address))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_street))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_city))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_pincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_pincode))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_gender)
                                    .addComponent(jRadioButton_female)
                                    .addComponent(jRadioButton_male)
                                    .addComponent(jRadioButton_other))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_department)
                                    .addComponent(jComboBox_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_designation)
                                    .addComponent(jComboBox_designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.WHITE);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.WHITE);//Set color of the icon
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.BLACK);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.WHITE);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.BLACK);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_deleteMouseClicked
       
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection cn = null;
            PreparedStatement st = null;
            ResultSet rs = null;
            
             //Get the username and password
            String fname = jTextField_firstname.getText();
            String lname = jTextField_lastname.getText();
            String phone = jTextField_phone.getText();
            String age = jTextField_age.getText();
            String address = jTextField_address.getText();
            String street = jTextField_street.getText();
            String city = jTextField_city.getText();
            String pincode = jTextField_pincode.getText();
            //Convert date_of_birth to string
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dob = sdf.format(jDateChooser_dob.getDate());

            String dep = jComboBox_department.getSelectedItem().toString();
            String desig = jComboBox_designation.getSelectedItem().toString();

            String gender;
            if(jRadioButton_male.isSelected())
            {
                gender = "Male";
            }
            else if(jRadioButton_female.isSelected())
            {
                gender = "Female";
            }
            else
            {
                gender = "Other";
            }

            //Create a DELETE query to delete data on the database
            String query = "DELETE FROM regs WHERE phone = "+phone;
            cn = MyCon.ConnectDB();
            st = cn.prepareStatement(query);
            
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "The record is deleted successfully");
            
            //Refresh Jtable contents
            DefaultTableModel model = (DefaultTableModel)jTable_show.getModel();
            model.setRowCount(0);
            show_user();
     
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ShowInfo_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ShowInfo_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jLabel_deleteMouseClicked

    private void jLabel_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_deleteMouseEntered
         //Set underline border for button
        Border label_border = BorderFactory.createMatteBorder(0,0,1,0,Color.BLACK);
        jLabel_delete.setBorder(label_border);
    }//GEN-LAST:event_jLabel_deleteMouseEntered

    private void jLabel_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_deleteMouseExited
        //No border
        jLabel_delete.setBorder(null);
    }//GEN-LAST:event_jLabel_deleteMouseExited

    private void jLabel_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_updateMouseClicked
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection cn = null;
            PreparedStatement st = null;
            ResultSet rs = null;

            //Get the username and password
            String fname = jTextField_firstname.getText();
            String lname = jTextField_lastname.getText();
            String phone = jTextField_phone.getText();
            String age = jTextField_age.getText();
            String address = jTextField_address.getText();
            String street = jTextField_street.getText();
            String city = jTextField_city.getText();
            String pincode = jTextField_pincode.getText();
            //Convert date_of_birth to string
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dob = sdf.format(jDateChooser_dob.getDate());

            String dep = jComboBox_department.getSelectedItem().toString();
            String desig = jComboBox_designation.getSelectedItem().toString();

            String gender;
            if(jRadioButton_male.isSelected())
            {
                gender = "Male";
            }
            else if(jRadioButton_female.isSelected())
            {
                gender = "Female";
            }
            else
            {
                gender = "Other";
            }

            //Create a UPDATE query to update data on the database
            String query = "UPDATE regs SET first_name=?,last_name=?,phone=?,age=?,address=?,"
                    + "street=?,city=?,pincode=?,dob=?,gender=?,department=?,designation=?"
                    + "WHERE `phone` = "+phone;
            cn = MyCon.ConnectDB();
            st = cn.prepareStatement(query);
            st.setString(1,fname);
            st.setString(2,lname);
            st.setString(3,phone);
            st.setString(4,age);
            st.setString(5,address);
            st.setString(6,street);
            st.setString(7,city);
            st.setString(8,pincode);
            st.setString(9,dob);
            st.setString(10,gender);
            st.setString(11,dep);
            st.setString(12,desig);

            boolean b1 = verifyFields();

            if(b1==true)
            {
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Your changes are updated");
            
            //Refresh Jtable contents
            DefaultTableModel model = (DefaultTableModel)jTable_show.getModel();
            model.setRowCount(0);
            show_user();
            }
            else{
            JOptionPane.showMessageDialog(null, "Retry!!!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ShowInfo_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ShowInfo_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel_updateMouseClicked

    private void jLabel_updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_updateMouseEntered
         //Set underline border for button
        Border label_border = BorderFactory.createMatteBorder(0,0,1,0,Color.BLACK);
        jLabel_update.setBorder(label_border);
    }//GEN-LAST:event_jLabel_updateMouseEntered

    private void jLabel_updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_updateMouseExited
        //No border
        jLabel_update.setBorder(null);
    }//GEN-LAST:event_jLabel_updateMouseExited

    private void jLabel_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_backMouseClicked
        //Progress to HomePage form
                Home_Page hp = new Home_Page();
                hp.setVisible(true);
                hp.pack();
                hp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                //Close ShowInfo form
                this.dispose();
    }//GEN-LAST:event_jLabel_backMouseClicked

    private void jLabel_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_backMouseEntered
         //Set underline border for button
        Border label_border = BorderFactory.createMatteBorder(0,0,1,0,Color.BLACK);
        jLabel_back.setBorder(label_border);
    }//GEN-LAST:event_jLabel_backMouseEntered

    private void jLabel_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_backMouseExited
         //No border
        jLabel_back.setBorder(null);
    }//GEN-LAST:event_jLabel_backMouseExited

    private void jTable_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_showMouseClicked
        //Display selected row in text fields
        int i = jTable_show.getSelectedRow();
        TableModel model = jTable_show.getModel();
        jTextField_firstname.setText(model.getValueAt(i,0).toString());
        jTextField_lastname.setText(model.getValueAt(i,1).toString());
        jTextField_phone.setText(model.getValueAt(i,2).toString());
        jTextField_age.setText(model.getValueAt(i,3).toString());
        jTextField_address.setText(model.getValueAt(i,4).toString());
        jTextField_street.setText(model.getValueAt(i,5).toString());
        jTextField_city.setText(model.getValueAt(i,6).toString());
        jTextField_pincode.setText(model.getValueAt(i,7).toString());
        
        java.util.Date dob = null;
        try {
            dob = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(i,8));
        } catch (ParseException ex) {
            Logger.getLogger(ShowInfo_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDateChooser_dob.setDate(dob);
        
        String gender = model.getValueAt(i,9).toString();
        if(gender.equals("Male"))
        {
            jRadioButton_male.setSelected(true);
            jRadioButton_female.setSelected(false);
            jRadioButton_other.setSelected(false);
        }
        else if(gender.equals("Female"))
        {
            jRadioButton_male.setSelected(false);
            jRadioButton_female.setSelected(true);
            jRadioButton_other.setSelected(false);
        }
        else
        {
            jRadioButton_male.setSelected(false);
            jRadioButton_female.setSelected(false);
            jRadioButton_other.setSelected(true);
        }
        
        String department = model.getValueAt(i,10).toString();
        switch(department)
        {
            case "IT":
                jComboBox_department.setSelectedIndex(0);
                break;
            case "Marketing":
                jComboBox_department.setSelectedIndex(1);
                break;
            case "Financial":
                jComboBox_department.setSelectedIndex(2);
                break; 
            case "Human Resources":
                jComboBox_department.setSelectedIndex(3);
                break; 
            case "Administration":
                jComboBox_department.setSelectedIndex(4);
                break; 
            case "Production":
                jComboBox_department.setSelectedIndex(5);
                break; 
            case "Logistics":
                jComboBox_department.setSelectedIndex(6);
                break; 
            case "Security":
                jComboBox_department.setSelectedIndex(7);
                break; 
        }
        
        String designation = model.getValueAt(i,11).toString();
        switch(designation)
        {
            case "Software Engineer":
                jComboBox_designation.setSelectedIndex(0);
                break;
            case "Trainee Engineer":
                jComboBox_designation.setSelectedIndex(1);
                break;
            case "System Analyst":
                jComboBox_designation.setSelectedIndex(2);
                break; 
            case "Programmer Analyst":
                jComboBox_designation.setSelectedIndex(3);
                break; 
            case "Project Manager":
                jComboBox_designation.setSelectedIndex(4);
                break; 
            case "Architect":
                jComboBox_designation.setSelectedIndex(5);
                break; 
            case "Technical Specialist":
                jComboBox_designation.setSelectedIndex(6);
                break; 
            case "Business Analyst":
                jComboBox_designation.setSelectedIndex(7);
                break;
            case "Director":
                jComboBox_designation.setSelectedIndex(8);
                break; 
            case "Vice President":
                jComboBox_designation.setSelectedIndex(9);
                break; 
            case "President":
                jComboBox_designation.setSelectedIndex(10);
                break; 
            case "CEO":
                jComboBox_designation.setSelectedIndex(11);
                break; 
        }
        
    }//GEN-LAST:event_jTable_showMouseClicked

    private void jTextField_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_firstnameActionPerformed

    private void jTextField_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lastnameActionPerformed

    private void jTextField_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phoneActionPerformed

    private void jTextField_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phoneKeyTyped
        //Allow only numbers
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_phoneKeyTyped

    private void jTextField_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ageActionPerformed

    private void jTextField_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ageKeyTyped
        //Allow only numbers
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_ageKeyTyped

    private void jTextField_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addressActionPerformed

    private void jTextField_streetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_streetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_streetActionPerformed

    private void jTextField_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cityActionPerformed

    private void jTextField_pincodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pincodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pincodeActionPerformed

    private void jTextField_pincodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_pincodeKeyTyped
        //Allow only numbers
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_pincodeKeyTyped

    private void jRadioButton_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_maleActionPerformed

    private void jRadioButton_otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_otherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_otherActionPerformed

    private void jComboBox_designationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_designationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_designationActionPerformed

    private void jLabel_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_searchMouseClicked
          JOptionPane.showMessageDialog(null, "Enter your respective search record and press \n ENTER");       
    }//GEN-LAST:event_jLabel_searchMouseClicked

    private void jLabel_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_searchMouseEntered
         //Set underline border for button
        Border label_border = BorderFactory.createMatteBorder(0,0,1,0,Color.WHITE);
        jLabel_search.setBorder(label_border);
    }//GEN-LAST:event_jLabel_searchMouseEntered

    private void jLabel_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_searchMouseExited
         //No border
        jLabel_search.setBorder(null);
    }//GEN-LAST:event_jLabel_searchMouseExited

    private void jTextField_firstnamesearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_firstnamesearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_firstnamesearchActionPerformed

    private void jTextField_lastname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lastname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lastname1ActionPerformed

    private void jTextField_phone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_phone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phone1ActionPerformed

    private void jTextField_phone1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phone1KeyTyped
          //Allow only numbers
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_phone1KeyTyped

    private void jTextField_firstnamesearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_firstnamesearchKeyReleased
        
            
    }//GEN-LAST:event_jTextField_firstnamesearchKeyReleased

    private void jTextField_lastname1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_lastname1KeyPressed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection cn = null;
            PreparedStatement st = null;
            ResultSet rs = null;
           
            //Create a SELECT query to search data on the database
            String query = "SELECT * FROM regs WHERE last_name = ?";
            cn = MyCon.ConnectDB();
            st = cn.prepareStatement(query);
            st.setString(1,jTextField_lastname1.getText());
            rs = st.executeQuery();
            
            if(rs.next())
            {
                String fname = rs.getString("first_name");
                jTextField_firstname.setText(fname);
                String lname = rs.getString("last_name");
                jTextField_lastname.setText(lname);
                String phone = rs.getString("phone");
                jTextField_phone.setText(phone);
                String age = rs.getString("age");
                jTextField_age.setText(age);
                String address = rs.getString("address");
                jTextField_address.setText(address);
                String street = rs.getString("street");
                jTextField_street.setText(street);
                String city = rs.getString("city");
                jTextField_city.setText(city);
                String pincode = rs.getString("pincode");
                jTextField_pincode.setText(pincode);
                
                
                jDateChooser_dob.setDate(rs.getDate("dob"));
                
                String gender = rs.getString("gender");
                if(gender.equals("Male"))
                {
                    jRadioButton_male.setSelected(true);
                    jRadioButton_female.setSelected(false);
                    jRadioButton_other.setSelected(false);
                }
                else if(gender.equals("Female"))
                {
                    jRadioButton_male.setSelected(false);
                    jRadioButton_female.setSelected(true);
                    jRadioButton_other.setSelected(false);
                }
                else
                {
                    jRadioButton_male.setSelected(false);
                    jRadioButton_female.setSelected(false);
                    jRadioButton_other.setSelected(true);
                }
                
                String department = rs.getString("department");
                switch(department)
                {
                    case "IT":
                        jComboBox_department.setSelectedIndex(0);
                        break;
                    case "Marketing":
                        jComboBox_department.setSelectedIndex(1);
                        break;
                    case "Financial":
                        jComboBox_department.setSelectedIndex(2);
                        break;
                    case "Human Resources":
                        jComboBox_department.setSelectedIndex(3);
                        break;
                    case "Administration":
                        jComboBox_department.setSelectedIndex(4);
                        break;
                    case "Production":
                        jComboBox_department.setSelectedIndex(5);
                        break;
                    case "Logistics":
                        jComboBox_department.setSelectedIndex(6);
                        break;
                    case "Security":
                        jComboBox_department.setSelectedIndex(7);
                        break;
                }
                
                String designation = rs.getString("designation");
                switch(designation)
                {
                    case "Software Engineer":
                        jComboBox_designation.setSelectedIndex(0);
                        break;
                    case "Trainee Engineer":
                        jComboBox_designation.setSelectedIndex(1);
                        break;
                    case "System Analyst":
                        jComboBox_designation.setSelectedIndex(2);
                        break;
                    case "Programmer Analyst":
                        jComboBox_designation.setSelectedIndex(3);
                        break;
                    case "Project Manager":
                        jComboBox_designation.setSelectedIndex(4);
                        break;
                    case "Architect":
                        jComboBox_designation.setSelectedIndex(5);
                        break;
                    case "Technical Specialist":
                        jComboBox_designation.setSelectedIndex(6);
                        break;
                    case "Business Analyst":
                        jComboBox_designation.setSelectedIndex(7);
                        break;
                    case "Director":
                        jComboBox_designation.setSelectedIndex(8);
                        break;
                    case "Vice President":
                        jComboBox_designation.setSelectedIndex(9);
                        break;
                    case "President":
                        jComboBox_designation.setSelectedIndex(10);
                        break;
                    case "CEO":
                        jComboBox_designation.setSelectedIndex(11);
                        break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ShowInfo_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ShowInfo_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField_lastname1KeyPressed

    private void jTextField_firstnamesearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_firstnamesearchKeyPressed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection cn = null;
            PreparedStatement st = null;
            ResultSet rs = null;
           
            //Create a SELECT query to search data on the database
            String query = "SELECT * FROM regs WHERE first_name = ?";
            cn = MyCon.ConnectDB();
            st = cn.prepareStatement(query);
            st.setString(1,jTextField_firstnamesearch.getText());
            rs = st.executeQuery();
            
            if(rs.next())
            {
                String fname = rs.getString("first_name");
                jTextField_firstname.setText(fname);
                String lname = rs.getString("last_name");
                jTextField_lastname.setText(lname);
                String phone = rs.getString("phone");
                jTextField_phone.setText(phone);
                String age = rs.getString("age");
                jTextField_age.setText(age);
                String address = rs.getString("address");
                jTextField_address.setText(address);
                String street = rs.getString("street");
                jTextField_street.setText(street);
                String city = rs.getString("city");
                jTextField_city.setText(city);
                String pincode = rs.getString("pincode");
                jTextField_pincode.setText(pincode);
                
                
                jDateChooser_dob.setDate(rs.getDate("dob"));
                
                String gender = rs.getString("gender");
                if(gender.equals("Male"))
                {
                    jRadioButton_male.setSelected(true);
                    jRadioButton_female.setSelected(false);
                    jRadioButton_other.setSelected(false);
                }
                else if(gender.equals("Female"))
                {
                    jRadioButton_male.setSelected(false);
                    jRadioButton_female.setSelected(true);
                    jRadioButton_other.setSelected(false);
                }
                else
                {
                    jRadioButton_male.setSelected(false);
                    jRadioButton_female.setSelected(false);
                    jRadioButton_other.setSelected(true);
                }
                
                String department = rs.getString("department");
                switch(department)
                {
                    case "IT":
                        jComboBox_department.setSelectedIndex(0);
                        break;
                    case "Marketing":
                        jComboBox_department.setSelectedIndex(1);
                        break;
                    case "Financial":
                        jComboBox_department.setSelectedIndex(2);
                        break;
                    case "Human Resources":
                        jComboBox_department.setSelectedIndex(3);
                        break;
                    case "Administration":
                        jComboBox_department.setSelectedIndex(4);
                        break;
                    case "Production":
                        jComboBox_department.setSelectedIndex(5);
                        break;
                    case "Logistics":
                        jComboBox_department.setSelectedIndex(6);
                        break;
                    case "Security":
                        jComboBox_department.setSelectedIndex(7);
                        break;
                }
                
                String designation = rs.getString("designation");
                switch(designation)
                {
                    case "Software Engineer":
                        jComboBox_designation.setSelectedIndex(0);
                        break;
                    case "Trainee Engineer":
                        jComboBox_designation.setSelectedIndex(1);
                        break;
                    case "System Analyst":
                        jComboBox_designation.setSelectedIndex(2);
                        break;
                    case "Programmer Analyst":
                        jComboBox_designation.setSelectedIndex(3);
                        break;
                    case "Project Manager":
                        jComboBox_designation.setSelectedIndex(4);
                        break;
                    case "Architect":
                        jComboBox_designation.setSelectedIndex(5);
                        break;
                    case "Technical Specialist":
                        jComboBox_designation.setSelectedIndex(6);
                        break;
                    case "Business Analyst":
                        jComboBox_designation.setSelectedIndex(7);
                        break;
                    case "Director":
                        jComboBox_designation.setSelectedIndex(8);
                        break;
                    case "Vice President":
                        jComboBox_designation.setSelectedIndex(9);
                        break;
                    case "President":
                        jComboBox_designation.setSelectedIndex(10);
                        break;
                    case "CEO":
                        jComboBox_designation.setSelectedIndex(11);
                        break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ShowInfo_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ShowInfo_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField_firstnamesearchKeyPressed

    private void jTextField_phone1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phone1KeyPressed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection cn = null;
            PreparedStatement st = null;
            ResultSet rs = null;
           
            //Create a SELECT query to search data on the database
            String query = "SELECT * FROM regs WHERE phone = ?";
            cn = MyCon.ConnectDB();
            st = cn.prepareStatement(query);
            st.setString(1,jTextField_phone1.getText());
            rs = st.executeQuery();
            
            if(rs.next())
            {
                String fname = rs.getString("first_name");
                jTextField_firstname.setText(fname);
                String lname = rs.getString("last_name");
                jTextField_lastname.setText(lname);
                String phone = rs.getString("phone");
                jTextField_phone.setText(phone);
                String age = rs.getString("age");
                jTextField_age.setText(age);
                String address = rs.getString("address");
                jTextField_address.setText(address);
                String street = rs.getString("street");
                jTextField_street.setText(street);
                String city = rs.getString("city");
                jTextField_city.setText(city);
                String pincode = rs.getString("pincode");
                jTextField_pincode.setText(pincode);
                
                
                jDateChooser_dob.setDate(rs.getDate("dob"));
                
                String gender = rs.getString("gender");
                if(gender.equals("Male"))
                {
                    jRadioButton_male.setSelected(true);
                    jRadioButton_female.setSelected(false);
                    jRadioButton_other.setSelected(false);
                }
                else if(gender.equals("Female"))
                {
                    jRadioButton_male.setSelected(false);
                    jRadioButton_female.setSelected(true);
                    jRadioButton_other.setSelected(false);
                }
                else
                {
                    jRadioButton_male.setSelected(false);
                    jRadioButton_female.setSelected(false);
                    jRadioButton_other.setSelected(true);
                }
                
                String department = rs.getString("department");
                switch(department)
                {
                    case "IT":
                        jComboBox_department.setSelectedIndex(0);
                        break;
                    case "Marketing":
                        jComboBox_department.setSelectedIndex(1);
                        break;
                    case "Financial":
                        jComboBox_department.setSelectedIndex(2);
                        break;
                    case "Human Resources":
                        jComboBox_department.setSelectedIndex(3);
                        break;
                    case "Administration":
                        jComboBox_department.setSelectedIndex(4);
                        break;
                    case "Production":
                        jComboBox_department.setSelectedIndex(5);
                        break;
                    case "Logistics":
                        jComboBox_department.setSelectedIndex(6);
                        break;
                    case "Security":
                        jComboBox_department.setSelectedIndex(7);
                        break;
                }
                
                String designation = rs.getString("designation");
                switch(designation)
                {
                    case "Software Engineer":
                        jComboBox_designation.setSelectedIndex(0);
                        break;
                    case "Trainee Engineer":
                        jComboBox_designation.setSelectedIndex(1);
                        break;
                    case "System Analyst":
                        jComboBox_designation.setSelectedIndex(2);
                        break;
                    case "Programmer Analyst":
                        jComboBox_designation.setSelectedIndex(3);
                        break;
                    case "Project Manager":
                        jComboBox_designation.setSelectedIndex(4);
                        break;
                    case "Architect":
                        jComboBox_designation.setSelectedIndex(5);
                        break;
                    case "Technical Specialist":
                        jComboBox_designation.setSelectedIndex(6);
                        break;
                    case "Business Analyst":
                        jComboBox_designation.setSelectedIndex(7);
                        break;
                    case "Director":
                        jComboBox_designation.setSelectedIndex(8);
                        break;
                    case "Vice President":
                        jComboBox_designation.setSelectedIndex(9);
                        break;
                    case "President":
                        jComboBox_designation.setSelectedIndex(10);
                        break;
                    case "CEO":
                        jComboBox_designation.setSelectedIndex(11);
                        break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ShowInfo_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ShowInfo_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField_phone1KeyPressed

    //Create a function to check for mandatory fields
    private boolean verifyFields()
    {
        String fname = jTextField_firstname.getText();
        String lname = jTextField_lastname.getText();
        String phone = jTextField_phone.getText();
        //String age = jTextField_age.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dob = sdf.format(jDateChooser_dob.getDate());

        //Check empty fields
        if((fname.trim().equals("")||lname.trim().equals("")||phone.trim().equals("")/*||age.trim().equals("")*/)
                ||(!(jRadioButton_male.isSelected()||jRadioButton_female.isSelected()
                ||jRadioButton_other.isSelected())))
        {
            JOptionPane.showMessageDialog(null, "Mandatory fields are empty","Empty Fields",2);
            return false;
        }
        else
        {
            return true;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowInfo_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowInfo_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowInfo_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowInfo_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowInfo_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_department;
    private javax.swing.JComboBox<String> jComboBox_designation;
    private com.toedter.calendar.JDateChooser jDateChooser_dob;
    private javax.swing.JLabel jLabel_address;
    private javax.swing.JLabel jLabel_age;
    private javax.swing.JLabel jLabel_back;
    private javax.swing.JLabel jLabel_city;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_delete;
    private javax.swing.JLabel jLabel_department;
    private javax.swing.JLabel jLabel_designation;
    private javax.swing.JLabel jLabel_dob;
    private javax.swing.JLabel jLabel_firstnamesearch;
    private javax.swing.JLabel jLabel_fullname;
    private javax.swing.JLabel jLabel_fullname5;
    private javax.swing.JLabel jLabel_gender;
    private javax.swing.JLabel jLabel_lastname;
    private javax.swing.JLabel jLabel_lastnamesearch;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_phone;
    private javax.swing.JLabel jLabel_phone1;
    private javax.swing.JLabel jLabel_pincode;
    private javax.swing.JLabel jLabel_search;
    private javax.swing.JLabel jLabel_street;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JLabel jLabel_update;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton_female;
    private javax.swing.JRadioButton jRadioButton_male;
    private javax.swing.JRadioButton jRadioButton_other;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_show;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_age;
    private javax.swing.JTextField jTextField_city;
    private javax.swing.JTextField jTextField_firstname;
    private javax.swing.JTextField jTextField_firstname5;
    private javax.swing.JTextField jTextField_firstnamesearch;
    private javax.swing.JTextField jTextField_lastname;
    private javax.swing.JTextField jTextField_lastname1;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_phone1;
    private javax.swing.JTextField jTextField_pincode;
    private javax.swing.JTextField jTextField_street;
    // End of variables declaration//GEN-END:variables
}
